-- Schema PostgreSQL para o MVP de pedidos da pizzaria.
-- O pedido do cliente no MVP atual e feito sem login.

DROP TABLE IF EXISTS itempedido;
DROP TABLE IF EXISTS item_pedido;
DROP TABLE IF EXISTS pagamento;
DROP TABLE IF EXISTS pedido;
DROP TABLE IF EXISTS produto;
DROP TABLE IF EXISTS cliente;
DROP TABLE IF EXISTS colaborador;

CREATE TABLE colaborador (
    id_colaborador INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_usuario VARCHAR(100) NOT NULL
        CHECK (TRIM(nome_usuario) <> ''),
    email_usuario VARCHAR(100) NOT NULL UNIQUE
        CHECK (TRIM(email_usuario) <> ''),
    senha_usuario VARCHAR(100) NOT NULL
        CHECK (TRIM(senha_usuario) <> '')
);

-- Tabela reservada para evolucao futura.
-- No MVP atual o cliente nao faz login e nao e obrigatorio para criar pedido.
CREATE TABLE cliente (
    id_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cliente VARCHAR(100) NOT NULL
        CHECK (TRIM(nome_cliente) <> ''),
    cpf_cliente VARCHAR(11) UNIQUE,
    celular_cliente VARCHAR(20),
    email_cliente VARCHAR(100) UNIQUE,
    senha_cliente VARCHAR(100)
);

CREATE TABLE produto (
    codprod INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_produto VARCHAR(100) NOT NULL
        CHECK (TRIM(nome_produto) <> ''),

    -- Categoria usada pelos filtros do cardapio no frontend.
    categoria VARCHAR(30) NOT NULL
        CHECK (categoria IN ('pizza', 'doce', 'bebida', 'combo')),

    preco NUMERIC(10, 2) NOT NULL
        CHECK (preco > 0),
    descricao TEXT,

    -- Controla se o produto aparece ou fica bloqueado no cardapio.
    status_disponibilidade VARCHAR(20) NOT NULL
        CHECK (status_disponibilidade IN ('disponivel', 'indisponivel')),

    estoque INT NOT NULL DEFAULT 0
        CHECK (estoque >= 0),
    imagem_url VARCHAR(200)
);

CREATE TABLE pedido (
    id_pedido INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) UNIQUE,

    -- O pedido guarda nome e telefone diretamente porque nao ha login de cliente no MVP.
    nome_cliente VARCHAR(100) NOT NULL
        CHECK (TRIM(nome_cliente) <> ''),
    telefone_cliente VARCHAR(20) NOT NULL
        CHECK (TRIM(telefone_cliente) <> ''),

    tipo_entrega VARCHAR(20) NOT NULL
        CHECK (tipo_entrega IN ('entrega', 'retirada')),
    rua_entrega VARCHAR(150),
    numero_entrega VARCHAR(20),
    bairro_entrega VARCHAR(100),
    complemento_entrega VARCHAR(150),
    observacoes TEXT,
    data_hora_pedido TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Status do fluxo operacional do Admin Pedidos.
    status_pedido VARCHAR(20) NOT NULL
        CHECK (status_pedido IN ('recebido', 'em_preparo', 'pronto', 'finalizado', 'cancelado')),

    valor_total NUMERIC(10, 2) NOT NULL
        CHECK (valor_total >= 0),

    CONSTRAINT chk_pedido_codigo_nao_vazio
        CHECK (codigo IS NULL OR TRIM(codigo) <> ''),

    CONSTRAINT chk_pedido_endereco_obrigatorio_entrega
        CHECK (
            tipo_entrega = 'retirada'
            OR (
                tipo_entrega = 'entrega'
                AND rua_entrega IS NOT NULL
                AND TRIM(rua_entrega) <> ''
                AND numero_entrega IS NOT NULL
                AND TRIM(numero_entrega) <> ''
                AND bairro_entrega IS NOT NULL
                AND TRIM(bairro_entrega) <> ''
            )
        )
);

CREATE TABLE pagamento (
    id_pagamento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INT NOT NULL,

    -- Forma escolhida pelo cliente; nao representa gateway real no MVP.
    forma_pagamento VARCHAR(20) NOT NULL,
    status_pagamento VARCHAR(20) NOT NULL DEFAULT 'pendente',
    valor_pago NUMERIC(10, 2) NOT NULL,
    data_hora_pagamento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_pagamento_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES pedido(id_pedido)
        ON DELETE RESTRICT,

    CONSTRAINT uq_pagamento_pedido
        UNIQUE (id_pedido),

    CONSTRAINT chk_pagamento_forma
        CHECK (forma_pagamento IN ('dinheiro', 'cartao', 'pix')),

    CONSTRAINT chk_pagamento_status
        CHECK (status_pagamento IN ('pendente', 'pago', 'cancelado')),

    CONSTRAINT chk_pagamento_valor
        CHECK (valor_pago >= 0)
);

CREATE TABLE itempedido (
    id_item_pedido INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INT NOT NULL,
    codprod INT NOT NULL,
    quantidade INT NOT NULL
        CHECK (quantidade > 0),
    preco_unitario NUMERIC(10, 2) NOT NULL
        CHECK (preco_unitario >= 0),
    subtotal NUMERIC(10, 2) NOT NULL
        CHECK (subtotal >= 0),

    CONSTRAINT fk_itempedido_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES pedido(id_pedido)
        ON DELETE RESTRICT,

    CONSTRAINT fk_itempedido_produto
        FOREIGN KEY (codprod)
        REFERENCES produto(codprod)
        ON DELETE RESTRICT
);
